export default {
  status: {
    pending: 'pending',
    fulfilled: 'fulfilled',
    rejected: 'rejected',
  },
  type: {
    characters: {
      FETCH_ALL_CHARACTERS: 'FETCH_ALL_CHARACTERS',
      FETCH_CHARACTER_BY_ID: 'FETCH_CHARACTER_BY_ID',
      FETCH_CHARACTERS_BY_NAME: 'FETCH_CHARACTERS_BY_NAME',
      FETCH_CHARACTERS_BY_CATEGORY: 'FETCH_CHARACTERS_BY_CATEGORY',
      FETCH_RANDOM_CHARACTER: 'FETCH_RANDOM_CHARACTER',
    },
    episodes: {
      FETCH_ALL_EPISODES: 'FETCH_ALL_EPISODES',
      FETCH_EPISODE_ATTRIBUTES: 'FETCH_EPISODE_ATTRIBUTES',
      FETCH_EPISODE_BY_ID: 'FETCH_EPISODE_BY_ID',
      FETCH_EPISODE_BY_SERIES: 'FETCH_EPISODE_BY_SERIES',
    },
    quotes: {
      FETCH_ALL_QUOTES: 'FETCH_ALL_QUOTES',
      FETCH_QUOTE_ATTRIBUTES: 'FETCH_QUOTE_ATTRIBUTES',
      FETCH_QUOTE_BY_ID: 'FETCH_QUOTE_BY_ID',
      FETCH_QUOTES_BY_SERIES: 'FETCH_QUOTES_BY_SERIES',
      FETCH_RANDOM_QUOTE: 'FETCH_RANDOM_QUOTE',
      FETCH_RANDOM_AUTHOR: 'FETCH_RANDOM_AUTHOR',
      FETCH_RANDOM_AUTHOR_BY_AUTHOR: 'FETCH_RANDOM_AUTHOR_BY_AUTHOR',
    },
    deaths: {
      FETCH_ALL_DEATHS: 'FETCH_ALL_DEATHS',
      FETCH_DEATH_BY_CHARACTER: 'FETCH_DEATH_BY_CHARACTER',
      FETCH_TOTAL_DEATH_COUNT_SERIES: 'FETCH_TOTAL_DEATH_COUNT_SERIES',
      FETCH_DEATH_COUNT_BY_CHARACTER: 'FETCH_DEATH_COUNT_BY_CHARACTER',
      FETCH_RANDOM_DEATH: 'FETCH_RANDOM_DEATH',
    },
  },
}
